#!/bin/sh
set -e

### Get db password in /pwfile
head -c 16 /dev/urandom  | sha1sum | cut -c1-10 > /pwfile
echo "PG_PASSWORD=$(cat /pwfile)"

### Check whether folders exist
if [ ! -d "/usr/share/zoneinfo" && ! -d "/data" ] ; then
    mkdir /usr/share/zoneinfo /data
    chown default /data
    su default -s /usr/bin/initdb -- --pgdata=/data --pwfile=/pwfile --username=postgres --auth=trust >/dev/null
fi
echo host all all 0.0.0.0 0.0.0.0 md5 >> /data/pg_hba.conf
exec su default -s /usr/bin/postgres -- -D /data -c 'listen_addresses=*'
